# Generated by Django 5.2.7 on 2026-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksp_naboj_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprogress',
            name='highest_unlocked_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
