# Generated by Django 5.2.7 on 2026-05-30 08:55

import importlib

from django.db import migrations, models

team_models = importlib.import_module("ksp-naboj.team.models")


class Migration(migrations.Migration):

    dependencies = [
        ('ksp_naboj_team', '0002_teamprogress_highest_unlocked_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='login_code',
            field=models.CharField(default=team_models._generate_login_code, max_length=16, unique=True),
        ),
    ]
