# Generated by Django 5.2.7 on 2026-05-30 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ksp_naboj_problem", "0002_remove_language_null"),
        ("ksp_naboj_team", "0003_add_login_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMemberActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("color_index", models.PositiveSmallIntegerField(default=0)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "current_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ksp_naboj_problem.problem",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="ksp_naboj_team.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "session_key")},
            },
        ),
    ]
