# Generated by Django 5.2.7 on 2026-04-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksp_naboj_competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
