# Generated by Django 5.2.7 on 2026-05-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksp_naboj_problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
